workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never

stages:         
  - build
  - deploy

build:   
  stage: build
  script:
    - echo "Compiling the code..."
    - CI="" yarn install
    - echo $ENV > .env
    - CI="" yarn build
    - echo "Compile complete."
    - echo "Deploying application..."
    - cp -r dist/* /var/www/ocpp-dashboard
    - chmod 777 /var/www/ocpp-dashboard --recursive
    - echo "Application successfully deployed."
